/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description Server-sent notifications. Handlers should do one thing: refetch.
         *
         *     Nothing here carries plan data, so live and replay share a single
         *     fetching path and the whole stream can be swapped for a poll.
         */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Presets */
        get: operations["get_presets_api_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/grid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Grid */
        get: operations["get_grid_api_sessions__session_id__grid_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_api_sessions__session_id__plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BlockOut */
        BlockOut: {
            /** Airmassmax */
            airmassMax: number;
            /** Airmassmin */
            airmassMin: number;
            /** Altitudeenddeg */
            altitudeEndDeg: number;
            /** Altitudemaxdeg */
            altitudeMaxDeg: number;
            /** Altitudemindeg */
            altitudeMinDeg: number;
            /** Altitudestartdeg */
            altitudeStartDeg: number;
            /** Azimuthenddeg */
            azimuthEndDeg: number;
            /** Azimuthstartdeg */
            azimuthStartDeg: number;
            /** Compass */
            compass: string;
            /** Dec */
            dec: string;
            /** Decdeg */
            decDeg: number;
            /**
             * Endsat
             * Format: date-time
             */
            endsAt: string;
            /** Expectedsnr */
            expectedSnr: number;
            /**
             * Integratingfrom
             * Format: date-time
             */
            integratingFrom: string;
            /** Integratingminutes */
            integratingMinutes: number;
            /** Meancloudfraction */
            meanCloudFraction: number;
            /** Meanefficiency */
            meanEfficiency: number;
            /** Meanpreference */
            meanPreference: number;
            /** Moonseparationmindeg */
            moonSeparationMinDeg: number;
            /** Nsubs */
            nSubs: number;
            /** Name */
            name: string;
            /** Ra */
            ra: string;
            /** Radeg */
            raDeg: number;
            /** Slotend */
            slotEnd: number;
            /** Slotstart */
            slotStart: number;
            /** Snrgoal */
            snrGoal: number;
            /**
             * Startsat
             * Format: date-time
             */
            startsAt: string;
            /** Switchminutes */
            switchMinutes: number;
            /** Tsubs */
            tSubS: number;
            /** Targetid */
            targetId: string;
            /** Warnings */
            warnings: components["schemas"]["WarningOut"][];
        };
        /** CatalogEntryOut */
        CatalogEntryOut: {
            /** Dec */
            dec: string;
            /** Decdeg */
            decDeg: number;
            /** Id */
            id: string;
            /** Magnitude */
            magnitude: number;
            /** Name */
            name: string;
            /** Ra */
            ra: string;
            /** Radeg */
            raDeg: number;
        };
        /** ChangesOut */
        ChangesOut: {
            /** Addedtargets */
            addedTargets: string[];
            /** Changedslots */
            changedSlots: number;
            /** Droppedtargets */
            droppedTargets: string[];
            /** Fromplanid */
            fromPlanId: string | null;
            /** Headline */
            headline: string;
            /** Lockedthroughslot */
            lockedThroughSlot: number;
            /** Pastslotsrewritten */
            pastSlotsRewritten: number;
        };
        /** DecisionPointOut */
        DecisionPointOut: {
            /** Addedtargets */
            addedTargets: string[];
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Changedslots */
            changedSlots: number;
            /** Droppedtargets */
            droppedTargets: string[];
            /** Index */
            index: number;
            /** Newestpublished */
            newestPublished: string | null;
            /** Planid */
            planId: string;
            /** Reason */
            reason: string;
            /** Recordsknown */
            recordsKnown: number;
        };
        /** DroppedOut */
        DroppedOut: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Name */
            name: string;
            /** Targetid */
            targetId: string;
        };
        /** EquipmentPresetOut */
        EquipmentPresetOut: {
            /** Aperturemm */
            apertureMm: number;
            /** Collectingareacm2 */
            collectingAreaCm2: number;
            /** Darkcurrentepers */
            darkCurrentEPerS: number;
            /** Focallengthmm */
            focalLengthMm: number;
            /** Focalratio */
            focalRatio: number;
            /** Fovheightdeg */
            fovHeightDeg: number;
            /** Fovwidthdeg */
            fovWidthDeg: number;
            /** Id */
            id: string;
            /** Minblockminutes */
            minBlockMinutes: number;
            /** Name */
            name: string;
            /** Pixelscalearcsec */
            pixelScaleArcsec: number;
            /** Pixelsizeum */
            pixelSizeUm: number;
            /** Quantumefficiency */
            quantumEfficiency: number;
            /** Readnoisee */
            readNoiseE: number;
            /** Switchminutes */
            switchMinutes: number;
            /** Throughput */
            throughput: number;
        };
        /** EvidenceOut */
        EvidenceOut: {
            /** Estimatedfraction */
            estimatedFraction: number;
            /** Hasoracle */
            hasOracle: boolean;
            /** Newestpublished */
            newestPublished: string | null;
            /** Records */
            records: number;
            /** Sources */
            sources: string[];
        };
        /** GridOut */
        GridOut: {
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Nslots */
            nSlots: number;
            /** Slotminutes */
            slotMinutes: number;
            /** Slotstarts */
            slotStarts: string[];
            /**
             * Start
             * Format: date-time
             */
            start: string;
        };
        /** GridRowOut */
        GridRowOut: {
            /** Airmass */
            airmass: number[];
            /** Altitudedeg */
            altitudeDeg: number[];
            /** Azimuthdeg */
            azimuthDeg: number[];
            /** Efficiency */
            efficiency: number[];
            /** Moonseparationdeg */
            moonSeparationDeg: number[];
            /** Name */
            name: string;
            /** Preference */
            preference: number[];
            /** Targetid */
            targetId: string;
            /** Visible */
            visible: boolean[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Sessions */
            sessions: number;
            /** Settings */
            settings: {
                [key: string]: string | boolean | number;
            };
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** MoonOut */
        MoonOut: {
            /** Altitudedeg */
            altitudeDeg: number[];
            /** Azimuthdeg */
            azimuthDeg: number[];
            /** Illumination */
            illumination: number[];
            /** Maxillumination */
            maxIllumination: number;
            /** Phaseangledeg */
            phaseAngleDeg: number[];
            /** Riseslot */
            riseSlot: number | null;
            /** Setslot */
            setSlot: number | null;
        };
        /** PlanOut */
        PlanOut: {
            /**
             * Asof
             * Format: date-time
             */
            asOf: string;
            /** Blocks */
            blocks: components["schemas"]["BlockOut"][];
            changes: components["schemas"]["ChangesOut"];
            /** Cloudfraction */
            cloudFraction: number[];
            /** Decisioncount */
            decisionCount: number;
            /** Decisionindex */
            decisionIndex: number;
            /** Dropped */
            dropped: components["schemas"]["DroppedOut"][];
            evidence: components["schemas"]["EvidenceOut"];
            /** Gap */
            gap: number;
            /** Objective */
            objective: number;
            /** Planid */
            planId: string;
            /** Progress */
            progress: components["schemas"]["TargetProgressOut"][];
            /** Reason */
            reason: string;
            /** Seeingfwhmarcsec */
            seeingFwhmArcsec: number[];
            /** Sessionid */
            sessionId: string;
            /** Slots */
            slots: components["schemas"]["SlotOut"][];
            /** Solvems */
            solveMs: number;
            /** Status */
            status: string;
            /** Summary */
            summary: string;
            /**
             * Validfrom
             * Format: date-time
             */
            validFrom: string;
            /**
             * Validuntil
             * Format: date-time
             */
            validUntil: string;
        };
        /** PresetsOut */
        PresetsOut: {
            /** Catalog */
            catalog: components["schemas"]["CatalogEntryOut"][];
            /** Defaulttargetids */
            defaultTargetIds: string[];
            /** Equipment */
            equipment: components["schemas"]["EquipmentPresetOut"][];
            /** Sites */
            sites: components["schemas"]["SitePresetOut"][];
        };
        /** QualityGridOut */
        QualityGridOut: {
            /**
             * Asof
             * Format: date-time
             */
            asOf: string;
            /** Cloudfraction */
            cloudFraction: number[];
            /** Nslots */
            nSlots: number;
            /** Planid */
            planId: string;
            /** Rows */
            rows: components["schemas"]["GridRowOut"][];
            /** Seeingfwhmarcsec */
            seeingFwhmArcsec: number[];
            /** Sessionid */
            sessionId: string;
        };
        /** SessionListItemOut */
        SessionListItemOut: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Decisionpoints */
            decisionPoints: number;
            /** Id */
            id: string;
            /** Ntargets */
            nTargets: number;
            /** Name */
            name: string;
            /**
             * Nightstart
             * Format: date-time
             */
            nightStart: string;
            /** Status */
            status: string;
        };
        /** SessionOut */
        SessionOut: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Decisionpoints */
            decisionPoints: components["schemas"]["DecisionPointOut"][];
            /** Distinctplans */
            distinctPlans: number;
            equipment: components["schemas"]["EquipmentPresetOut"];
            /** Error */
            error?: string | null;
            /** Foldseconds */
            foldSeconds: number;
            grid: components["schemas"]["GridOut"];
            /** Id */
            id: string;
            /** Message */
            message: string;
            moon: components["schemas"]["MoonOut"];
            /** Name */
            name: string;
            /** Progress */
            progress: number;
            site: components["schemas"]["SitePresetOut"];
            /** Status */
            status: string;
            /** Sunaltitudedeg */
            sunAltitudeDeg: number[];
            /** Targets */
            targets: components["schemas"]["TargetOut"][];
            /** Twilight */
            twilight: components["schemas"]["TwilightBandOut"][];
            /** Weathersource */
            weatherSource: string;
        };
        /** SessionRequest */
        SessionRequest: {
            /**
             * Date
             * @description night start date, UTC, YYYY-MM-DD
             */
            date: string;
            /**
             * Equipmentid
             * @default sct8-2600mm
             */
            equipmentId: string;
            /**
             * Hours
             * @default 8
             */
            hours: number;
            /** Name */
            name?: string | null;
            /** @description overrides siteId when present */
            site?: components["schemas"]["SiteRequest"] | null;
            /**
             * Siteid
             * @default urbana
             */
            siteId: string | null;
            /**
             * Slotminutes
             * @default 5
             */
            slotMinutes: number;
            /**
             * Snrgoal
             * @default 60
             */
            snrGoal: number;
            /**
             * Solveseconds
             * @default 4
             */
            solveSeconds: number;
            /**
             * Starthourutc
             * @default 1
             */
            startHourUtc: number;
            /**
             * Tsubs
             * @default 90
             */
            tSubS: number;
            /** Targets */
            targets?: components["schemas"]["TargetRequest"][] | null;
            /**
             * Weather
             * @description 'synthetic' (offline, deterministic) or 'open_meteo' (real archived runs)
             * @default synthetic
             */
            weather: string;
        };
        /** SitePresetOut */
        SitePresetOut: {
            /** Artificialzenithnl */
            artificialZenithNl: number;
            /** Bortle */
            bortle: number;
            /** Elevationm */
            elevationM: number;
            /** Extinctionk */
            extinctionK: number;
            /** Id */
            id: string;
            /** Latitudedeg */
            latitudeDeg: number;
            /** Longitudedeg */
            longitudeDeg: number;
            /** Name */
            name: string;
            /** Zenithskymagarcsec2 */
            zenithSkyMagArcsec2: number;
        };
        /** SiteRequest */
        SiteRequest: {
            /**
             * Bortle
             * @default 5
             */
            bortle: number;
            /**
             * Elevationm
             * @default 0
             */
            elevationM: number;
            /**
             * Extinctionk
             * @default 0.2
             */
            extinctionK: number;
            /** Latitudedeg */
            latitudeDeg: number;
            /**
             * Longitudedeg
             * @description positive EAST
             */
            longitudeDeg: number;
            /**
             * Minaltitudedeg
             * @default 30
             */
            minAltitudeDeg: number;
            /**
             * Minmoonseparationdeg
             * @default 15
             */
            minMoonSeparationDeg: number;
            /**
             * Name
             * @default custom
             */
            name: string;
        };
        /** SlotOut */
        SlotOut: {
            /** Kind */
            kind: string;
            /** Locked */
            locked: boolean;
            /** Slot */
            slot: number;
            /** Targetid */
            targetId: string | null;
        };
        /** TargetOut */
        TargetOut: {
            /** Dec */
            dec: string;
            /** Decdeg */
            decDeg: number;
            /** Id */
            id: string;
            /** Magnitude */
            magnitude: number;
            /** Maxaltitudedeg */
            maxAltitudeDeg: number;
            /** Name */
            name: string;
            /** Priority */
            priority: number;
            /** Ra */
            ra: string;
            /** Radeg */
            raDeg: number;
            /** Requiredrefminutes */
            requiredRefMinutes: number;
            /** Snrgoal */
            snrGoal: number;
            /** Transitslot */
            transitSlot: number | null;
            /** Urgency */
            urgency: number;
            /** Visibleslots */
            visibleSlots: number;
        };
        /** TargetProgressOut */
        TargetProgressOut: {
            /** Accumulatedrefminutes */
            accumulatedRefMinutes: number;
            /** Expectedsnr */
            expectedSnr: number;
            /** Fraction */
            fraction: number;
            /** Included */
            included: boolean;
            /** Name */
            name: string;
            /** Observingslots */
            observingSlots: number;
            /** Requiredrefminutes */
            requiredRefMinutes: number;
            /** Snrgoal */
            snrGoal: number;
            /** Targetid */
            targetId: string;
        };
        /** TargetRequest */
        TargetRequest: {
            /** Decdeg */
            decDeg?: number | null;
            /** Id */
            id: string;
            /**
             * Magnitude
             * @description V surface brightness, mag/arcsec^2
             */
            magnitude?: number | null;
            /** Name */
            name?: string | null;
            /**
             * Priority
             * @default 1
             */
            priority: number;
            /** Radeg */
            raDeg?: number | null;
            /** Snrgoal */
            snrGoal?: number | null;
            /**
             * Urgency
             * @default 1
             */
            urgency: number;
        };
        /** TwilightBandOut */
        TwilightBandOut: {
            /**
             * Endsat
             * Format: date-time
             */
            endsAt: string;
            /** Fromslot */
            fromSlot: number;
            /** Kind */
            kind: string;
            /**
             * Startsat
             * Format: date-time
             */
            startsAt: string;
            /** Toslot */
            toSlot: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WarningOut */
        WarningOut: {
            /** Action */
            action: string;
            /** Severity */
            severity: string;
            /** Text */
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    get_presets_api_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetsOut"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListItemOut"][];
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_grid_api_sessions__session_id__grid_get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityGridOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_sessions__session_id__plan_get: {
        parameters: {
            query?: {
                /** @description ISO-8601 instant. The plan in force then; omitted means dusk. */
                as_of?: string | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
